[project]
name = "ollama-ai-agent-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.44.1",
    "mcp-server-git>=2025.7.1",
    "praisonaiagents[llm]>=0.0.162",
]
